export const THRESHOLDS = {
  MICROCOMPACT_UTILIZATION: 0.50,
  AUTOCOMPACT_UTILIZATION: 0.85,
  BLOCKED_UTILIZATION: 0.95,
} as const

export const SNIP_COMPACT_THRESHOLD = 0.70
export const SNIP_TARGET_USAGE = 0.60
export const SNIP_MIN_MESSAGES_TO_REMOVE = 6
export const SNIP_KEEP_RECENT_MESSAGES = 12
export const SNIP_MIN_TOKENS_TO_FREE = 2_000

export const RETENTION = {
  KEEP_RECENT_TOOL_RESULTS: 3,
  MIN_KEEP_MESSAGES: 6,
  MIN_KEEP_TOKENS: 10_000,
  MAX_KEEP_TOKENS: 40_000,
} as const

export const LIMITS = {
  MAX_AUTOCOMPACT_FAILURES: 3,
  SUMMARY_MAX_OUTPUT_TOKENS: 4_096,
  PTL_MAX_RETRIES: 2,
  MIN_EFFECTIVE_INPUT_FOR_AUTOCOMPACT: 20_000,
} as const
