export const THRESHOLDS = {
  MICROCOMPACT_UTILIZATION: 0.50,
  AUTOCOMPACT_UTILIZATION: 0.85,
  BLOCKED_UTILIZATION: 0.95,
} as const

export const RETENTION = {
  KEEP_RECENT_TOOL_RESULTS: 3,
  MIN_KEEP_MESSAGES: 6,
  MIN_KEEP_TOKENS: 10_000,
  MAX_KEEP_TOKENS: 40_000,
} as const

export const LIMITS = {
  MAX_AUTOCOMPACT_FAILURES: 3,
  SUMMARY_MAX_OUTPUT_TOKENS: 4_096,
  PTL_MAX_RETRIES: 2,
  MIN_EFFECTIVE_INPUT_FOR_AUTOCOMPACT: 20_000,
} as const
